apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-code-battle
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://forgejo.ardenone.com/ai-code-battle/ai-code-battle.git
    targetRevision: master
    path: cluster-configuration/apexalgo-iad/ai-code-battle
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-code-battle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
