apiVersion: v1
kind: Service
metadata:
  name: acb-strategy-hunter
  namespace: ai-code-battle
  labels:
    app.kubernetes.io/name: acb-strategy-hunter
    app.kubernetes.io/part-of: ai-code-battle
    app.kubernetes.io/component: strategy-bot
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: acb-strategy-hunter
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
