.PHONY: all gatherer random guardian hunter rusher swarm clean

all: gatherer random guardian hunter rusher swarm

gatherer:
	cd gatherer && chmod +x build.sh && ./build.sh

random:
	cd random && chmod +x build.sh && ./build.sh

guardian:
	cd guardian && chmod +x build.sh && ./build.sh

hunter:
	cd hunter && chmod +x build.sh && ./build.sh

rusher:
	cd rusher && chmod +x build.sh && ./build.sh

swarm:
	cd swarm && chmod +x build.sh && ./build.sh

clean:
	rm -rf dist
	mkdir -p dist
