// Rivalries page: display pre-computed head-to-head rivalries from
// data/meta/rivalries.json (generated by index builder §13.5).

import { fetchRivalries, type RivalryEntry } from '../api-types';

// ─── Page render ─────────────────────────────────────────────────────────────

export async function renderRivalriesPage(_params: Record<string, string>): Promise<void> {
  const app = document.getElementById('app');
  if (!app) return;

  app.innerHTML = `
    <div class="rivalries-page">
      <h1 class="page-title">Rivalries</h1>
      <p class="page-subtitle">Head-to-head storylines from the most contested matchups on the grid.</p>
      <div id="rivalries-content" class="loading">Loading rivalries…</div>
    </div>
    ${RIVALRY_STYLES}
  `;

  const content = document.getElementById('rivalries-content')!;

  try {
    const { rivalries } = await fetchRivalries();

    if (rivalries.length === 0) {
      content.innerHTML = `
        <div class="empty-state">
          <p>No rivalries detected yet.</p>
          <p class="hint">Rivalries appear when two bots have played at least 10 head-to-head matches.
             Check back after more matches have been recorded.</p>
        </div>
      `;
      return;
    }

    renderRivalryCards(content, rivalries);
  } catch (err) {
    content.innerHTML = `<div class="error">Failed to load rivalry data: ${err}</div>`;
  }
}

// ─── Card renderer ────────────────────────────────────────────────────────────

function renderRivalryCards(container: HTMLElement, rivalries: RivalryEntry[]): void {
  container.innerHTML = `
    <div class="rivalry-grid">
      ${rivalries.map((r, i) => `
        <div class="rivalry-card ${i === 0 ? 'featured' : ''}">
          ${i === 0 ? '<div class="rivalry-badge">Top Rivalry</div>' : ''}
          <div class="rivalry-header">
            <div class="rivalry-combatant">
              <a href="#/bot/${r.bot_a.id}" class="combatant-name">${escapeHtml(r.bot_a.name)}</a>
              <span class="combatant-record">${r.record.a_wins}W</span>
            </div>
            <div class="rivalry-vs">
              <span class="vs-text">VS</span>
              <span class="rivalry-total">${r.matches} matches</span>
            </div>
            <div class="rivalry-combatant right">
              <a href="#/bot/${r.bot_b.id}" class="combatant-name">${escapeHtml(r.bot_b.name)}</a>
              <span class="combatant-record">${r.record.b_wins}W</span>
            </div>
          </div>

          <div class="win-bar-container">
            ${buildWinBar(r)}
          </div>

          <p class="rivalry-narrative">${escapeHtml(r.narrative)}</p>

          <div class="rivalry-footer">
            ${r.longest_streak ? `<span class="streak-badge">${escapeHtml(r.longest_streak.holder)}'s ${r.longest_streak.length}-win streak</span>` : ''}
            ${r.record.draws > 0 ? `<span class="draws-tag">${r.record.draws} draw${r.record.draws !== 1 ? 's' : ''}</span>` : ''}
            ${r.closest_match ? `<a href="#/watch/replay/${r.closest_match}" class="btn small secondary">Closest Match</a>` : ''}
          </div>
        </div>
      `).join('')}
    </div>
  `;
}

function buildWinBar(r: RivalryEntry): string {
  const total = r.matches;
  const pctA = total > 0 ? (r.record.a_wins / total) * 100 : 50;
  const pctD = total > 0 ? (r.record.draws / total) * 100 : 0;
  const pctB = 100 - pctA - pctD;
  return `
    <div class="win-bar">
      <div class="win-bar-seg seg0" style="width:${pctA.toFixed(1)}%" title="${r.bot_a.name}: ${r.record.a_wins} wins"></div>
      <div class="win-bar-seg seg-draw" style="width:${pctD.toFixed(1)}%" title="Draws: ${r.record.draws}"></div>
      <div class="win-bar-seg seg1" style="width:${pctB.toFixed(1)}%" title="${r.bot_b.name}: ${r.record.b_wins} wins"></div>
    </div>
    <div class="win-bar-labels">
      <span style="color:#3b82f6">${r.record.a_wins}W (${pctA.toFixed(0)}%)</span>
      <span style="color:#94a3b8">${r.record.draws > 0 ? r.record.draws + ' draws' : ''}</span>
      <span style="color:#ef4444">${pctB.toFixed(0)}% (${r.record.b_wins}W)</span>
    </div>
  `;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const RIVALRY_STYLES = `
<style>
.rivalries-page .page-subtitle { color: var(--text-muted); margin-bottom: 24px; }
.rivalry-grid { display: flex; flex-direction: column; gap: 16px; }
.rivalry-card { background: var(--bg-secondary); border-radius: 10px; padding: 20px; position: relative; border: 1px solid var(--border); }
.rivalry-card.featured { border-color: var(--accent); box-shadow: 0 0 0 1px var(--accent); }
.rivalry-badge { position: absolute; top: -1px; right: 20px; background: var(--accent); color: #fff; font-size: 0.7rem; font-weight: 700; padding: 3px 10px; border-radius: 0 0 6px 6px; text-transform: uppercase; letter-spacing: 0.05em; }
.rivalry-header { display: grid; grid-template-columns: 1fr auto 1fr; align-items: center; gap: 16px; margin-bottom: 12px; }
.rivalry-combatant { display: flex; flex-direction: column; gap: 4px; }
.rivalry-combatant.right { align-items: flex-end; text-align: right; }
.combatant-name { color: var(--text-primary); text-decoration: none; font-size: 1.1rem; font-weight: 600; }
.combatant-name:hover { color: var(--accent); }
.combatant-record { font-size: 0.875rem; color: var(--text-muted); }
.rivalry-vs { text-align: center; }
.vs-text { display: block; font-size: 1.25rem; font-weight: 800; color: var(--text-muted); }
.rivalry-total { font-size: 0.7rem; color: var(--text-muted); }
.win-bar-container { margin: 12px 0; }
.win-bar { height: 10px; border-radius: 5px; overflow: hidden; display: flex; }
.win-bar-seg { height: 100%; }
.seg0 { background: #3b82f6; }
.seg-draw { background: #475569; }
.seg1 { background: #ef4444; }
.win-bar-labels { display: flex; justify-content: space-between; font-size: 0.7rem; margin-top: 4px; }
.rivalry-narrative { color: var(--text-muted); font-style: italic; font-size: 0.875rem; margin: 12px 0; line-height: 1.5; }
.rivalry-footer { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; margin-top: 12px; }
.streak-badge { background: rgba(245,158,11,0.15); color: var(--warning); font-size: 0.75rem; padding: 3px 8px; border-radius: 12px; }
.draws-tag { background: var(--bg-tertiary); color: var(--text-muted); font-size: 0.75rem; padding: 3px 8px; border-radius: 12px; }
.empty-state { background: var(--bg-secondary); border-radius: 8px; padding: 40px; text-align: center; color: var(--text-muted); }
.empty-state .hint { margin-top: 10px; font-size: 0.875rem; }
</style>
`;
